name: 'Auto Refresh Gitee Pages'
description: '自动刷新gitee pages服务'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: refresh-cw
  color: red
inputs:
  username:
    description: '用户名'
    required: true
  password:
    description: '密码'
    required: true
  repository:
    description: '仓库网址'
    required: true
  branch:
    description: '部署分支'
    required: false
    default: master
  directory:
    description: '部署目录'
    required: false
    default: ''
  https:
    description: '开启https'
    required: false
    default: 'true'

