name: Test gitee-pages
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          username: okou19900722
          password: ${{ secrets.GITEE_PASSWORD }}
          repository: "https://gitee.com/okou19900722/svg-path-editor"
          branch: test
