name: Test gitee-pages
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          username: okou19900722
          password: ${{ secrets.GITEE_PASSWORD }}
          repository: "https://gitee.com/vertx-china/vertx-china"
